name: release

#on:
#  push:
#    tags:
#      - '*'
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Install "Box"
        run: composer global require humbug/box

      - name: Compile code
        run: box -v
